[package]
name = "purple-telegraf-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
telegraf = "*"
reqwest = {version= "0.11", features=["json", "blocking"]}
serde = "*"
serde_derive = "*"
openssl = "*"

[features]
vendored-openssl = ["openssl/vendored"]
